apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  selector:
    matchLabels:
      app: petclinic-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic-pod
    spec:
      containers:
      - name: petclinic
        image: tanzukr.azurecr.io/app/springpetclinic2:latest
        ports:
        - containerPort: 8080
          name: http-web
---        
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-service
spec:
  ports:
  - port: 80
    targetPort: http-web
  selector:
    app: petclinic-pod
  type: LoadBalancer
