apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/has-tests : "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"

